### ISSUE TITLE
File not found: main.js

### ISSUE THREAD

**Issue by dotherightthing** [yakuhzi/github-release#4] opened 2020-07-08 01:10 UTC
I just updated to the latest version of action-release and am receiving the following error. I'm not sure whether this is due to a problem in action-release, or because I did not specify the `file` argument (I don't want to attach any files to this release):

```
Run yakuhzi/action-release@v1.2.2
  with:
    changelog: changelog/CHANGELOG.md
  env:
    GITHUB_TOKEN: ***
##[error]File not found: '/home/runner/work/_actions/yakuhzi/action-release/v1.2.2/dist/main.js'
```

**Comment by dotherightthing** [comment] 2020-07-08 11:12
Downgrading to `yakuhzi/action-release@v1.2.0` fixed my issue.

However then I received this warning:

> Unexpected input 'changelog', valid inputs are ['file', 'changelogs']

Despite this warning, my changelog did appear in the release description.

**Comment by yakuhzi** [comment] 2020-07-08 17:23
Could you check if the issue is also present, if you use yakuhzi/action-release@v1? 
It should also point to the latest release, but this one is working for me.

Regarding the warning: Back in v1.2.0 there was a typo in the action.yml file, where it says changelogs instead of changelog, but in code it was always changelog. This was fixed in 2ecf7e0d40ccb4cc77631dbca8c56f64f2731ac4.

**Comment by dotherightthing** [comment] 2020-07-08 20:50
I 'downgraded' to `yakuhzi/action-release@v1` and everything is now working perfectly, thanks. There are no errors or warnings, and the changelog appears in the release.

**Closed as completed** 2020-07-12 10:40 UTC

**Comment by yakuhzi** [comment] 2020-07-17 15:34
I just found out the issue: The tag v1.2.2 was pointing to the master branch instead of the releases/v1 branch where the dist files are available.
